
Person.delete_all
State.delete_all
State.create(name:'Alabama', abrv: 'AL', capital: 'Montgomery')
State.create(name:'Alaska', abrv: 'AK', capital: 'Juneau')
State.create(name:'Arizona', abrv: 'AZ', capital: 'Phoenix')
State.create(name:'Arkansas', abrv: 'AR', capital: 'Little Rock')
State.create(name:'California', abrv: 'CA', capital: 'Sacramento')
State.create(name:'Colorado', abrv: 'CO', capital: 'Denver')
State.create(name:'Connecticut', abrv: 'CT', capital: 'Hartford')
State.create(name:'Delaware', abrv: 'DE', capital: 'Dover')
State.create(name:'Florida', abrv: 'FL', capital: 'Tallahassee')
State.create(name:'Georgia', abrv: 'GA', capital: 'Atlanta')
State.create(name:'Hawaii', abrv: 'HI', capital: 'Honolulu')
State.create(name:'Idaho', abrv: 'ID', capital: 'Boise')
State.create(name:'Illinois', abrv: 'IL', capital: 'Springfield')
State.create(name:'Indiana', abrv: 'IN', capital: 'Indianapolis')
State.create(name:'Iowa', abrv: 'IA', capital: 'Des Moines')
State.create(name:'Kansas', abrv: 'KS', capital: 'Topeka')
State.create(name:'Kentucky', abrv: 'KY', capital: 'Frankfort')
State.create(name:'Louisiana', abrv: 'LA', capital: 'Baton Rouge')
State.create(name:'Maine', abrv: 'ME', capital: 'Augusta')
State.create(name:'Maryland', abrv: 'MD', capital: 'Annapolis')
State.create(name:'Massachusetts', abrv: 'MA', capital: 'Boston')
State.create(name:'Michigan', abrv: 'MI', capital: 'Lansing')
State.create(name:'Minnesota', abrv: 'MN', capital: 'St. Paul')
State.create(name:'Mississippi', abrv: 'MS', capital: 'Jackson')
State.create(name:'Missouri', abrv: 'MO', capital: 'Jefferson City')
State.create(name:'Montana', abrv: 'MT', capital: 'Helena')
State.create(name:'Nebraska', abrv: 'NE', capital: 'Lincoln')
State.create(name:'Nevada', abrv: 'NV', capital: 'Carson City')
State.create(name:'New Hampshire', abrv: 'NH', capital: 'Concord')
State.create(name:'New Jersey', abrv: 'NJ', capital: 'Trenton')
State.create(name:'New Mexico', abrv: 'NM', capital: 'Santa Fe')
State.create(name:'New York', abrv: 'NY', capital: 'Albany')
State.create(name:'North Carolina', abrv: 'NC', capital: 'Raleigh')
State.create(name:'North Dakota', abrv: 'ND', capital: 'Bismarck')
State.create(name:'Ohio', abrv: 'OH', capital: 'Columbus')
State.create(name:'Oklahoma', abrv: 'OK', capital: 'Oklahoma City')
State.create(name:'Oregon', abrv: 'OR', capital: 'Salem')
State.create(name:'Pennsylvania', abrv: 'PA', capital: 'Harrisburg')
State.create(name:'Rhode Island', abrv: 'RI', capital: 'Providence')
State.create(name:'South Carolina', abrv: 'SC', capital: 'Columbia')
State.create(name:'South Dakota', abrv: 'SD', capital: 'Pierre')
State.create(name:'Tennessee', abrv: 'TN', capital: 'Nashville')
State.create(name:'Texas', abrv: 'TX', capital: 'Austin')
State.create(name:'Utah', abrv: 'UT', capital: 'Salt Lake City')
State.create(name:'Vermont', abrv: 'VT', capital: 'Montpelier')
State.create(name:'Virginia', abrv: 'VA', capital: 'Richmond')
State.create(name:'Washington', abrv: 'WA', capital: 'Olympia')
State.create(name:'West Virginia', abrv: 'WV', capital: 'Charleston')
State.create(name:'Wisconsin', abrv: 'WI', capital: 'Madison')
State.create(name:'Wyoming', abrv: 'WY', capital: 'Cheyenne')



